package cmd

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/dev-toolings/pvecli/internal/config"
	"github.com/dev-toolings/pvecli/internal/iac"
	"github.com/dev-toolings/pvecli/internal/pve"
	"github.com/dev-toolings/pvecli/internal/testutil"
)

// inventoryRoutes describes a lab with one of every case the generator has to
// deal with, taken from the real /cluster/resources?type=vm of the lab node:
//
//	lxc/120    a stopped container — nothing to connect to
//	qemu/211   running, answers  — the only host that makes it in
//	qemu/212   running, silent   — its agent route is deliberately absent
//	qemu/213   stopped           — nothing to interrogate
//	qemu/9000  a template        — not a host
func inventoryRoutes() map[string]string {
	return map[string]string{
		"GET /api2/json/cluster/resources":                               "cluster-resources-vm.json",
		"GET /api2/json/nodes/pve/qemu/211/agent/network-get-interfaces": "agent-ifaces.json",
		"GET /api2/json/nodes/pve/qemu/211/config":                       "qemu-config.json",
	}
}

// The inventory carries an address the guest reported, and only that.
func TestInventoryTakesItsAddressFromTheAgent(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatalf("iac inventory a échoué : %v", err)
	}

	for _, want := range []string{
		"GENERATED BY pvecli",
		"lab:",                 // the group comes from the PVE tag
		"lab-app-01:",          // the host is named after the guest
		"203.0.113.10",         // the address the agent reported
		"ansible_user: debian", // read from cloud-init's ciuser
	} {
		if !strings.Contains(stdout, want) {
			t.Errorf("l'inventaire ne contient pas %q :\n%s", want, stdout)
		}
	}
}

// The criterion that matters most in this story: nothing is dropped in silence.
//
// Each of these four guests is absent from the document for a different reason,
// and an operator who cannot see the reason will conclude the fleet is smaller
// than it is.
func TestExcludedGuestsAreNamedOnStderr(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, stderr, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatal(err)
	}

	cases := map[string]string{
		// 120 is a container, and containers are no longer excluded for being
		// containers: this one is out because it is stopped.
		"120":  "conteneur arrêté",
		"212":  "agent QEMU muet",
		"213":  "arrêtée",
		"9000": "template",
	}
	for vmid, reason := range cases {
		if !strings.Contains(stderr, "exclu "+vmid) || !strings.Contains(stderr, reason) {
			t.Errorf("le guest %s doit être exclu ET expliqué (%q) :\n%s", vmid, reason, stderr)
		}
		if strings.Contains(stdout, "vmid: "+vmid) {
			t.Errorf("le guest %s exclu ne doit pas figurer dans le document", vmid)
		}
	}
}

// stdout carries the document, stderr everything else. Otherwise
// `pvecli iac inventory > inv.yml` writes a file Ansible cannot parse.
func TestOnlyTheDocumentGoesToStdout(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(stdout, "exclu ") {
		t.Errorf("une explication a fui sur stdout :\n%s", stdout)
	}
	if !strings.HasPrefix(stdout, "#") {
		t.Errorf("stdout doit commencer par l'en-tête généré :\n%s", stdout)
	}
}

func TestInventoryUserFlagOverridesCloudInit(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve", "--user", "ops")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stdout, "ansible_user: ops") {
		t.Errorf("--user doit l'emporter sur ciuser :\n%s", stdout)
	}
	// And the config read becomes pointless, so it must not happen.
	for _, req := range srv.Requests {
		if strings.HasSuffix(req, "/qemu/211/config") {
			t.Errorf("--user fourni : la configuration cloud-init n'a pas à être lue (%v)", srv.Requests)
		}
	}
}

func TestInventoryTagFilter(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, stderr, err := run(t, "iac", "inventory", "--node", "pve", "--tag", "lxc")
	if err != nil {
		t.Fatal(err)
	}
	// « lxc » n'est porté que par le conteneur 120 de la fixture (les qemu
	// portent « lab » et « template;debian13 »). Il est donc filtré-in, puis
	// exclu parce qu'il est arrêté : le document est vide et le dit.
	//
	// L'exclusion nommée sur stderr est ce qui PROUVE le filtrage-in : sans
	// elle, un inventaire vide satisferait aussi un filtre sur-exclusif qui
	// n'aurait rien retenu du tout.
	if strings.Contains(stdout, "lab-app-01") {
		t.Errorf("--tag lxc ne doit pas retenir lab-app-01 :\n%s", stdout)
	}
	for _, want := range []string{"exclu 120 (web)", "arrêté"} {
		if !strings.Contains(stderr, want) {
			t.Errorf("le 120 doit être filtré-in puis exclu, et stderr doit le dire (%q absent) :\n%s", want, stderr)
		}
	}
	if !strings.Contains(stderr, "aucun hôte") {
		t.Errorf("un inventaire vide doit le dire :\n%s", stderr)
	}
}

func TestInventoryWritesTheFileAndKeepsStdoutClean(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	path := filepath.Join(t.TempDir(), "inventory.yml")
	stdout, stderr, err := run(t, "iac", "inventory", "--node", "pve", "-o", path)
	if err != nil {
		t.Fatal(err)
	}
	if stdout != "" {
		t.Errorf("avec -o, stdout doit rester vide : %q", stdout)
	}
	if !strings.Contains(stderr, path) {
		t.Errorf("stderr doit dire où le fichier a été écrit : %q", stderr)
	}

	body, err := os.ReadFile(path) //nolint:gosec // path built by the test
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), "203.0.113.10") {
		t.Errorf("le fichier écrit ne contient pas l'inventaire :\n%s", body)
	}
}

// --format json is the same tree, not a second document. `ansible-inventory -i`
// reads it because JSON is a subset of YAML.
func TestInventoryJSONCarriesTheSameTree(t *testing.T) {
	srv := testutil.New(t, "../testdata", inventoryRoutes())
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve", "--format", "json")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{`"all"`, `"children"`, `"lab"`, `"ansible_host": "203.0.113.10"`} {
		if !strings.Contains(stdout, want) {
			t.Errorf("le JSON ne contient pas %s :\n%s", want, stdout)
		}
	}
}

// stubTool puts a fake binary first in PATH and records how it was called.
//
// The wrapped tools are installed on the machine this was written on; the stub
// exists to make the invocation observable, not to avoid the dependency.
func stubTool(t *testing.T, name, stdout string) (calls string) {
	t.Helper()

	dir := t.TempDir()
	calls = filepath.Join(dir, "calls")
	script := "#!/bin/sh\n" +
		"{ printf 'argv: %s\\n' \"$*\"; printf 'TF_VAR_proxmox_api_token=%s\\n' \"$TF_VAR_proxmox_api_token\"; } >> " + calls + "\n" +
		"printf '%s\\n'\n"
	if stdout != "" {
		script = "#!/bin/sh\n" +
			"{ printf 'argv: %s\\n' \"$*\"; printf 'TF_VAR_proxmox_api_token=%s\\n' \"$TF_VAR_proxmox_api_token\"; } >> " + calls + "\n" +
			"cat <<'EOS'\n" + stdout + "\nEOS\n"
	}
	if err := os.WriteFile(filepath.Join(dir, name), []byte(script), 0o755); err != nil { //nolint:gosec // a test stub must be executable
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	return calls
}

// The criterion of PVX-046: the token reaches Terraform through the
// environment, and never through terraform.tfvars. A secret in a file gets
// committed — this project refuses it in its OWN config file, and has no reason
// to be more relaxed about someone else's.
func TestTheTokenReachesTerraformThroughTheEnvironmentOnly(t *testing.T) {
	tfDir := t.TempDir()
	calls := stubTool(t, "terraform", `{"format_version":"1.0"}`)

	cfg := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(cfg, []byte(
		"current_context: test\ncontexts:\n  test:\n    iac:\n      terraform_dir: "+tfDir+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PVECLI_CONFIG", cfg)
	t.Setenv("TF_VAR_proxmox_api_token", "")

	srv := testutil.New(t, "../testdata", map[string]string{
		"GET /api2/json/version": "version.json",
	})
	point(t, srv.URL)

	if _, _, err := run(t, "iac", "plan", "--node", "pve"); err != nil {
		t.Fatalf("iac plan : %v", err)
	}

	body, err := os.ReadFile(calls) //nolint:gosec // path built by the test
	if err != nil {
		t.Fatal(err)
	}
	got := string(body)

	if !strings.Contains(got, "TF_VAR_proxmox_api_token=automation@pve!pvectl=s3cr3t") {
		t.Errorf("le token doit arriver par l'environnement, au format <token-id>=<secret> :\n%s", got)
	}
	if !strings.Contains(got, "argv: plan") {
		t.Errorf("terraform doit être appelé en « plan » :\n%s", got)
	}
	// Nothing was written next to the .tf files.
	entries, err := os.ReadDir(tfDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		t.Errorf("pvecli n'écrit rien dans le dossier terraform : %v", entries)
	}
}

// The bpg/proxmox provider has no ca_file attribute. pvecli must therefore
// pass the configured CA to Terraform through Go's standard SSL_CERT_FILE
// trust-pool hook, while keeping verification enabled.
func TestConfiguredCAReachesTerraformWithoutDisablingTLS(t *testing.T) {
	t.Setenv("TF_VAR_proxmox_api_token", "")
	t.Setenv("SSL_CERT_FILE", "/a/different/ca.pem")

	c := &cobra.Command{}
	c.SetErr(io.Discard)
	env := terraformEnv(c, &config.Effective{
		TokenID:     "automation@pve!pvectl",
		TokenSecret: "s3cr3t",
		TLS:         config.TLS{CAFile: "/etc/pve/pve-root-ca.pem"},
	})
	got := strings.Join(env, "\n")

	if !strings.Contains(got, "SSL_CERT_FILE=/etc/pve/pve-root-ca.pem") {
		t.Errorf("la CA configurée doit atteindre Terraform : %s", got)
	}
	if !strings.Contains(got, "TF_VAR_proxmox_api_token=automation@pve!pvectl=s3cr3t") {
		t.Errorf("le token doit continuer à atteindre Terraform : %s", got)
	}
	if strings.Contains(got, "insecure=true") {
		t.Errorf("le correctif TLS ne doit pas désactiver la vérification : %s", got)
	}
}

// --dry-run on apply runs plan. Anything else would make the flag a promise the
// command does not keep.
func TestApplyDryRunRunsPlan(t *testing.T) {
	tfDir := t.TempDir()
	calls := stubTool(t, "terraform", `{"format_version":"1.0"}`)

	cfg := filepath.Join(t.TempDir(), "config.yaml")
	if err := os.WriteFile(cfg, []byte(
		"current_context: test\ncontexts:\n  test:\n    iac:\n      terraform_dir: "+tfDir+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PVECLI_CONFIG", cfg)

	srv := testutil.New(t, "../testdata", map[string]string{"GET /api2/json/version": "version.json"})
	point(t, srv.URL)

	if _, _, err := run(t, "iac", "apply", "--dry-run", "--node", "pve"); err != nil {
		t.Fatalf("iac apply --dry-run : %v", err)
	}

	body, _ := os.ReadFile(calls) //nolint:gosec // path built by the test
	if strings.Contains(string(body), "argv: apply") {
		t.Errorf("--dry-run ne doit jamais lancer « apply » :\n%s", body)
	}
	if !strings.Contains(string(body), "argv: plan") {
		t.Errorf("--dry-run doit lancer « plan » :\n%s", body)
	}
}

// A container has no agent, so its address can only come from what it declares.
// This table pins the decision for each shape the configuration can take —
// including the two that are deliberately refused rather than guessed.
func TestLXCStaticIPv4ReadsTheConfigurationAndRefusesToGuess(t *testing.T) {
	cases := []struct {
		name       string
		cfg        pve.GuestConfig
		wantIP     string
		wantReason []string // substrings the exclusion must contain
		denyReason []string // substrings it must NOT contain, to discriminate the motives
	}{
		{
			name:   "une IPv4 statique : le masque ne va pas dans ansible_host",
			cfg:    pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,hwaddr=BC:24:11:45:5C:E7,ip=192.168.1.222/24,gw=192.168.1.1"},
			wantIP: "192.168.1.222",
		},
		{
			name:   "une IPv4 sans masque reste lisible",
			cfg:    pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=10.0.0.5"},
			wantIP: "10.0.0.5",
		},
		{
			name:       "un bail DHCP n'est pas une adresse",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=dhcp"},
			wantReason: []string{"dhcp", "net0"},
		},
		{
			name:       "« manual » non plus",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=manual"},
			wantReason: []string{"manual"},
		},
		{
			name: "deux IPv4 statiques : la configuration ne tranche pas",
			cfg: pve.GuestConfig{
				"net0": "name=eth0,bridge=vmbr0,ip=10.0.0.5/24",
				"net1": "name=eth1,bridge=vmbr1,ip=192.168.1.30/24",
			},
			wantReason: []string{"plusieurs", "net0=10.0.0.5", "net1=192.168.1.30"},
		},
		{
			name:       "aucune interface déclarée",
			cfg:        pve.GuestConfig{"hostname": "edge-01"},
			wantReason: []string{"aucune interface réseau"},
		},
		{
			name:       "une interface sans adresse du tout",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0"},
			wantReason: []string{"aucune adresse déclarée", "net0"},
		},
		{
			name:       "seulement de l'IPv6 : l'inventaire ne pose que de l'IPv4",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip6=2001:db8::1/64,ip=2001:db8::1/64"},
			wantReason: []string{"IPv6"},
		},
		{
			name:       "une valeur qui ne parse pas n'est pas propagée",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=pas-une-adresse"},
			wantReason: []string{"illisible", "net0 ip=pas-une-adresse"},
			denyReason: []string{"bail", "IPv6"},
		},
		{
			name:       "une IPv4 illisible avec une IPv6 valide n'est pas « seulement de l'IPv6 »",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=pas-une-adresse,ip6=2001:db8::1/64"},
			wantReason: []string{"illisible", "net0 ip=pas-une-adresse"},
			denyReason: []string{"bail", "seulement une IPv6"},
		},
		// Ces trois-là parsent en IPv4 et ne joignent pourtant pas le conteneur :
		// « ssh 0.0.0.0 » atteint la machine qui lance pvecli.
		{
			name:       "la loopback ne désigne pas le conteneur",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=127.0.0.1/8"},
			wantReason: []string{"inutilisable pour joindre", "net0 ip=127.0.0.1/8"},
			denyReason: []string{"bail", "illisible"},
		},
		{
			name:       "l'adresse non spécifiée non plus",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=0.0.0.0/0"},
			wantReason: []string{"inutilisable pour joindre", "net0 ip=0.0.0.0/0"},
			denyReason: []string{"bail", "illisible"},
		},
		{
			name:       "le lien-local ne survit pas au premier saut",
			cfg:        pve.GuestConfig{"net0": "name=eth0,bridge=vmbr0,ip=169.254.1.5/16"},
			wantReason: []string{"inutilisable pour joindre", "net0 ip=169.254.1.5/16"},
			denyReason: []string{"bail", "illisible"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ip, reason := lxcStaticIPv4(tc.cfg)
			if tc.wantIP != "" {
				if ip != tc.wantIP {
					t.Fatalf("ip = %q (motif %q), attendu %q", ip, reason, tc.wantIP)
				}
				if reason != "" {
					t.Errorf("une adresse trouvée ne doit pas porter de motif d'exclusion : %q", reason)
				}
				return
			}
			if ip != "" {
				t.Fatalf("aucune adresse n'était décidable, %q rendue", ip)
			}
			if reason == "" {
				t.Fatal("une exclusion sans motif est exactement ce que ce dépôt refuse")
			}
			for _, want := range tc.wantReason {
				if !strings.Contains(reason, want) {
					t.Errorf("le motif doit dire ce qui a été lu (%q absent) : %s", want, reason)
				}
			}
			for _, deny := range tc.denyReason {
				if strings.Contains(reason, deny) {
					t.Errorf("le motif raconte autre chose que ce qui a été lu (%q présent) : %s", deny, reason)
				}
			}
		})
	}
}

// lxcFixtures writes a cluster shaped like the real one — CT 222 « edge-01 »
// carrying svc_caddy, plus one container per refusal — and returns the fixture
// directory and its routes.
//
// Written here rather than captured under testdata/ because the point is the
// variation: five containers that differ only by one field of one config.
func lxcFixtures(t *testing.T) (dir string, routes map[string]string) {
	t.Helper()

	dir = t.TempDir()
	write := func(name, body string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	write("resources.json", `{"data":[
	  {"id":"lxc/222","vmid":222,"name":"edge-01","node":"pve","type":"lxc","status":"running","template":0,"tags":"edge;pvecli;svc_caddy"},
	  {"id":"lxc/230","vmid":230,"name":"ct-dhcp","node":"pve","type":"lxc","status":"running","template":0,"tags":"lab"},
	  {"id":"lxc/231","vmid":231,"name":"ct-double","node":"pve","type":"lxc","status":"running","template":0,"tags":"lab"},
	  {"id":"lxc/232","vmid":232,"name":"ct-modele","node":"pve","type":"lxc","status":"stopped","template":1,"tags":"template"},
	  {"id":"lxc/233","vmid":233,"name":"ct-arrete","node":"pve","type":"lxc","status":"stopped","template":0,"tags":"lab"}
	]}`)
	write("ct-222.json", `{"data":{"hostname":"edge-01","ostype":"debian",
	  "net0":"name=eth0,bridge=vmbr0,hwaddr=BC:24:11:45:5C:E7,ip=192.168.1.222/24,gw=192.168.1.1,type=veth"}}`)
	write("ct-230.json", `{"data":{"hostname":"ct-dhcp","net0":"name=eth0,bridge=vmbr0,hwaddr=BC:24:11:00:00:01,ip=dhcp,type=veth"}}`)
	write("ct-231.json", `{"data":{"hostname":"ct-double",
	  "net0":"name=eth0,bridge=vmbr0,hwaddr=BC:24:11:00:00:02,ip=10.0.0.5/24,type=veth",
	  "net1":"name=eth1,bridge=vmbr1,hwaddr=BC:24:11:00:00:03,ip=192.168.1.30/24,type=veth"}}`)

	return dir, map[string]string{
		"GET /api2/json/cluster/resources":        "resources.json",
		"GET /api2/json/nodes/pve/lxc/222/config": "ct-222.json",
		"GET /api2/json/nodes/pve/lxc/230/config": "ct-230.json",
		"GET /api2/json/nodes/pve/lxc/231/config": "ct-231.json",
	}
}

// The defect this fixes: CT 222 carries svc_caddy, the catalogue has a
// « hosts: svc_caddy » play, and the container was excluded — so the play ran on
// zero hosts and reported green.
func TestInventoryTakesAContainerAddressFromItsConfiguration(t *testing.T) {
	dir, routes := lxcFixtures(t)
	srv := testutil.New(t, dir, routes)
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatalf("iac inventory a échoué : %v", err)
	}

	for _, want := range []string{
		"svc_caddy:",                  // the group the play targets
		"edge-01:",                    // the container is a host
		"ansible_host: 192.168.1.222", // read in net0, without its mask
		"ansible_user: root",          // the only account PVE guarantees
	} {
		if !strings.Contains(stdout, want) {
			t.Errorf("l'inventaire ne contient pas %q :\n%s", want, stdout)
		}
	}
	if strings.Contains(stdout, "192.168.1.222/24") {
		t.Errorf("le masque n'a rien à faire dans ansible_host :\n%s", stdout)
	}
}

func TestInventoryUserFlagOverridesTheContainerDefault(t *testing.T) {
	dir, routes := lxcFixtures(t)
	srv := testutil.New(t, dir, routes)
	point(t, srv.URL)

	stdout, _, err := run(t, "iac", "inventory", "--node", "pve", "--user", "ops")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(stdout, "ansible_user: ops") {
		t.Errorf("--user doit l'emporter sur le « root » par défaut :\n%s", stdout)
	}
	if strings.Contains(stdout, "ansible_user: root") {
		t.Errorf("« root » ne doit plus apparaître quand --user est donné :\n%s", stdout)
	}
}

// Each container left out is left out for its own reason, and the reason says
// what was read. None of them mentions a QEMU agent: a container has none, and
// that was never why it could not be reached.
func TestExcludedContainersSayWhatWasReadInTheirConfiguration(t *testing.T) {
	dir, routes := lxcFixtures(t)
	srv := testutil.New(t, dir, routes)
	point(t, srv.URL)

	stdout, stderr, err := run(t, "iac", "inventory", "--node", "pve")
	if err != nil {
		t.Fatal(err)
	}

	cases := map[string][]string{
		"230": {"dhcp"},                                            // a lease is not an address
		"231": {"plusieurs", "net0=10.0.0.5", "net1=192.168.1.30"}, // undecidable
		"232": {"template"},                                        // excluded as a template, not as a container
		"233": {"conteneur arrêté"},                                // stopped, and not "the agent cannot answer"
	}
	for vmid, wants := range cases {
		line := ""
		for _, l := range strings.Split(stderr, "\n") {
			if strings.HasPrefix(l, "exclu "+vmid+" ") {
				line = l
			}
		}
		if line == "" {
			t.Errorf("le conteneur %s doit être exclu ET expliqué :\n%s", vmid, stderr)
			continue
		}
		for _, want := range wants {
			if !strings.Contains(line, want) {
				t.Errorf("le motif de %s doit contenir %q : %s", vmid, want, line)
			}
		}
		if strings.Contains(line, "agent") {
			t.Errorf("le motif de %s parle d'agent QEMU, qu'un conteneur n'a pas : %s", vmid, line)
		}
		if strings.Contains(stdout, "vmid: "+vmid) {
			t.Errorf("le conteneur %s exclu ne doit pas figurer dans le document", vmid)
		}
	}
}

// Le pré-vol doit porter le même --limit que le playbook.
//
// Observé sur le lab : « iac configure --limit hermes-ephemeral-01 » refusait
// de démarrer parce que 220 et 221, hors sujet, ne répondaient pas en SSH. Le
// ping interrogeait « all » en dur, donc n'importe quelle machine éteinte de
// l'inventaire interdisait un run visant une seule VM parfaitement joignable.
// Un garde-fou qui bloque des runs sains finit contourné.
func TestThePreflightPingCarriesTheSameLimitAsThePlaybook(t *testing.T) {
	calls := stubTool(t, "ansible", `hermes-ephemeral-01 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}`)

	c := &cobra.Command{}
	c.SetContext(t.Context())
	c.SetErr(io.Discard)
	if err := pingHosts(c, iac.Tool{Name: "ansible"}, "/tmp/inv.yml", "hermes-ephemeral-01"); err != nil {
		t.Fatalf("pré-vol : %v", err)
	}

	body, err := os.ReadFile(calls) //nolint:gosec // path built by the test
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), "--limit hermes-ephemeral-01") {
		t.Errorf("le --limit du run doit atteindre le ping :\n%s", body)
	}
}

// Sans --limit, rien ne change : le pré-vol interroge tout l'inventaire.
// La restriction est une réponse à une demande explicite, pas un défaut.
func TestThePreflightPingWithoutLimitStillAsksEveryHost(t *testing.T) {
	calls := stubTool(t, "ansible", `edge-01 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}`)

	c := &cobra.Command{}
	c.SetContext(t.Context())
	c.SetErr(io.Discard)
	if err := pingHosts(c, iac.Tool{Name: "ansible"}, "/tmp/inv.yml", ""); err != nil {
		t.Fatalf("pré-vol : %v", err)
	}

	body, _ := os.ReadFile(calls) //nolint:gosec // path built by the test
	if strings.Contains(string(body), "--limit") {
		t.Errorf("sans --limit demandé, le ping ne doit en poser aucun :\n%s", body)
	}
}
